/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Problema1;

/**
 *
 * @author linkh
 */
public class Problema1GUI extends javax.swing.JFrame {

    /**
     * Creates new form Problema1GUI
     */
    public Problema1GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Filosofo1 = new javax.swing.JLabel();
        Filosofo2 = new javax.swing.JLabel();
        Filosofo3 = new javax.swing.JLabel();
        Filosofo4 = new javax.swing.JLabel();
        Filosofo5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tenedor1 = new javax.swing.JLabel();
        tenedor2 = new javax.swing.JLabel();
        tenedor3 = new javax.swing.JLabel();
        tenedor4 = new javax.swing.JLabel();
        tenedor5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        iniciarBoton = new javax.swing.JButton();
        terminarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Filosofo1.setBackground(new java.awt.Color(51, 102, 255));
        Filosofo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Filosofo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/socrates.png"))); // NOI18N
        Filosofo1.setText("FILOSOFO 1");
        Filosofo1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Filosofo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Filosofo1.setOpaque(true);
        Filosofo1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        Filosofo2.setBackground(new java.awt.Color(51, 51, 255));
        Filosofo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Filosofo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/socrates.png"))); // NOI18N
        Filosofo2.setText("FILOSOFO 2");
        Filosofo2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Filosofo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Filosofo2.setOpaque(true);
        Filosofo2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        Filosofo3.setBackground(new java.awt.Color(0, 102, 255));
        Filosofo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Filosofo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/socrates.png"))); // NOI18N
        Filosofo3.setText("FILOSOFO 3");
        Filosofo3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Filosofo3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Filosofo3.setOpaque(true);
        Filosofo3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        Filosofo4.setBackground(new java.awt.Color(0, 51, 255));
        Filosofo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Filosofo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/socrates.png"))); // NOI18N
        Filosofo4.setText("FILOSOFO 4");
        Filosofo4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Filosofo4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Filosofo4.setOpaque(true);
        Filosofo4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        Filosofo5.setBackground(new java.awt.Color(0, 0, 255));
        Filosofo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Filosofo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/socrates.png"))); // NOI18N
        Filosofo5.setText("FILOSOFO 5");
        Filosofo5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Filosofo5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Filosofo5.setOpaque(true);
        Filosofo5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mesa.png"))); // NOI18N

        tenedor1.setBackground(new java.awt.Color(0, 204, 0));
        tenedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tenedor.png"))); // NOI18N
        tenedor1.setText("TENEDOR 1");
        tenedor1.setOpaque(true);

        tenedor2.setBackground(new java.awt.Color(0, 204, 0));
        tenedor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tenedor.png"))); // NOI18N
        tenedor2.setText("TENEDOR 2");
        tenedor2.setOpaque(true);

        tenedor3.setBackground(new java.awt.Color(0, 204, 0));
        tenedor3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tenedor.png"))); // NOI18N
        tenedor3.setText("TENEDOR 3");
        tenedor3.setOpaque(true);

        tenedor4.setBackground(new java.awt.Color(0, 204, 0));
        tenedor4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tenedor.png"))); // NOI18N
        tenedor4.setText("TENEDOR 4");
        tenedor4.setOpaque(true);

        tenedor5.setBackground(new java.awt.Color(0, 204, 0));
        tenedor5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tenedor.png"))); // NOI18N
        tenedor5.setText("TENEDOR 5");
        tenedor5.setOpaque(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("TENEDORES");

        jLabel3.setBackground(new java.awt.Color(51, 204, 0));
        jLabel3.setText("Libre");
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("Ocupado");
        jLabel4.setOpaque(true);

        jLabel5.setText("FILOSOFOS");

        jLabel6.setBackground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("Pensando");
        jLabel6.setOpaque(true);

        jLabel7.setBackground(new java.awt.Color(0, 204, 51));
        jLabel7.setText("Comiendo");
        jLabel7.setOpaque(true);

        jLabel8.setBackground(new java.awt.Color(255, 255, 102));
        jLabel8.setText("Un tenedor");
        jLabel8.setOpaque(true);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Entro a comer");
        jLabel9.setOpaque(true);

        iniciarBoton.setText("Iniciar");

        terminarBoton.setText("Terminar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(iniciarBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(terminarBoton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(iniciarBoton)
                                .addComponent(terminarBoton)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(tenedor1)
                .addGap(108, 108, 108)
                .addComponent(Filosofo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tenedor5)
                .addGap(68, 68, 68))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Filosofo2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tenedor2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Filosofo3)
                        .addGap(53, 53, 53)
                        .addComponent(tenedor3)
                        .addGap(43, 43, 43)
                        .addComponent(Filosofo4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Filosofo5)
                            .addComponent(tenedor4))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tenedor5)
                    .addComponent(Filosofo1)
                    .addComponent(tenedor1))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(Filosofo5)
                                .addGap(56, 56, 56)
                                .addComponent(tenedor4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(Filosofo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tenedor2)
                        .addGap(33, 33, 33)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Filosofo3)
                    .addComponent(Filosofo4)
                    .addComponent(tenedor3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Problema1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Problema1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Problema1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Problema1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Problema1GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Filosofo1;
    private javax.swing.JLabel Filosofo2;
    private javax.swing.JLabel Filosofo3;
    private javax.swing.JLabel Filosofo4;
    private javax.swing.JLabel Filosofo5;
    private javax.swing.JButton iniciarBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tenedor1;
    private javax.swing.JLabel tenedor2;
    private javax.swing.JLabel tenedor3;
    private javax.swing.JLabel tenedor4;
    private javax.swing.JLabel tenedor5;
    private javax.swing.JButton terminarBoton;
    // End of variables declaration//GEN-END:variables
}
